name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up Python
      uses: actions/setup-python@v4.6.1
      with:
        python-version: '3.x'

    - name: Install Hatch and mypy
      run: pip install --upgrade hatch mypy

    - name: Build and publish
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
      run: |
        hatch version $GITHUB_REF_NAME
        stubgen aioworkers_boto -o ./
        hatch build
        hatch publish
